### ISSUE TITLE
Дополнительные способы подтвердить пользователя при регистрации

### ISSUE THREAD

**Issue by vitaliiplatonov** [apanasenko/tabmaker#21]
Фидбек пользователя:
> Я попытался зарегестрироваться пару дней назад, однако письмо на почту до сих пор не пришло. Не могли бы Вы решить данную проблему как можно быстрее? 

Обратите внимание:
1. об этом регулярно пишут в саппорт
2. это может задержать весь турнир (нужно зарегистрировать команду прямо перед турниром, никто не понимает, почему не приходит письмо, а во Владивостоке ночь либо мы пропустили запрос в техподдержку)
3. вероятно, невозможность зарегистрироваться бесит пользователей и организаторов

**Comment by apanasenko** [comment]
Нет, проблема в том, что они не могут правильно свой емеил ввести

**Comment by vitaliiplatonov** [comment]
> Нет, проблема в том, что они не могут правильно свой емеил ввести

Ты прав, но это не решает проблему и заставляет (нас) просить каждого пользователя вводить email заново, что они (почему-то) не могут сделать. Давайте подумаем, есть ли лучшее решение

**Comment by vitaliiplatonov** [comment]
И кроме неправильной почты есть такие случаи:
> Не получается перейти по ссылке в письме и закончить регистрацию

**Comment by apanasenko** [comment]
Вроде находил сервис для проверки емейлов налету. Нужно его подключить.
